---
- name: Start labs
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Start lab
      cisco.cml.cml_lab:
        host: "198.18.133.103"
        username: "admin"
        password: "C1sco12345"
        lab: "{{ item }}"
        state: started
      loop: "{{ labs }}"